package com.ptt.gateway.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "audit_logs")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AuditLog {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "uuid")
    private UUID id;

    /**
     * Auto-generated by PostgreSQL trigger: AE0001, AH0001, UM0001, RL0001
     * Do NOT set this from Java — let the DB trigger handle it.
     */
    @Column(name = "event_name", length = 10, insertable = false, updatable = false)
    private String eventName;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "severity", nullable = false, length = 20)
    private String severity; // INFO, WARNING, ERROR

    @Column(name = "status_type", length = 50)
    private String statusType; // SUCCESS, FAILED, Action, Delete, etc.

    @Column(name = "created_by", length = 255)
    private String createdBy; // username from JWT

    @Column(name = "source", nullable = false, length = 100)
    private String source; // AUTH_SERVICE, BACKEND, NGINX, etc.

    @Column(name = "client_ip", length = 100)
    private String clientIp;

    @Column(name = "action", length = 255)
    private String action; // machine key: "updateShipper"

    @Column(name = "description", columnDefinition = "TEXT")
    private String description; // human-readable for frontend

    @Column(name = "access_method", length = 50)
    private String accessMethod; // local, ad

    @Column(name = "log_type", nullable = false, length = 50)
    private String logType; // ACTION, ACCESS_HISTORY, USER_MANAGEMENT, NGINX_ACCESS

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "metadata", columnDefinition = "jsonb")
    private String metadata; // serialized JSON string

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
